name: CI for Formatter and Linter

on:
  push:
    branches:
      - master  # ou main, selon ta branche par défaut
  pull_request:
    branches:
      - master  # ou main

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Utilise la version Python que tu veux

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit

    - name: Run pre-commit hooks for formatting
      run: |
        source venv/bin/activate
        pre-commit run --all-files  # Exécute tous les hooks, y compris black

  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Utilise la version Python que tu veux

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit

    - name: Run pre-commit hooks for linting
      run: |
        source venv/bin/activate
        pre-commit run --all-files  
